### ISSUE TITLE
Suggestion: In-Game Example Compendium

### ISSUE THREAD

**Issue by Nargath** [Haxxer/FoundryVTT-Sequencer#3]
For the coding illiterate like me, I cannot get your examples to work.
As you build the examples, are you able to include them in an in-game macro compendium?

That way those that learn by ripping apart other people's functional code will have fully end-to-end complete macros to work with :)

**Comment by Haxxer** [comment]
What examples aren't working? :) Do you have the .webm files in those same locations as the examples?

**Comment by Nargath** [comment]
Its more that I think they aren't fully complete? Again, code-dumb here.

In the youtube vid, and in the teleport instance, you have
**let sequence = New Sequence()**
But in examples, its just **new Sequence()**

And then in the teleport instance, you have **sequence.play();** in the final line, but **.play();** in the other examples

I've definitely figured out changing the path to point to my direct animations, and not having the .effect path to your default.

I just figured that having some easy-as-pie drag and drop examples that work to a tee will benefit those of us who have no coding experience.
This module looks amazing to be able to drop anything into it, coupled with the other animation tools in Foundry, so the more people that can get into it, the better!

**Comment by Haxxer** [comment]
Fair - there's just many ways to do the same thing, really! If you want to re-use the same sequence multiple times, then putting it in  a variable is useful, but if you're just looking to play it once then you can just do `new Sequence()` and end it with `.play()`.

I'll clean up the documentation so that they're consistent, and perhaps I'll provide some real example macros in the 0.3.10 release 👍

**Comment by Haxxer** [comment]
Added in 0.3.10
